---

- name: Create custom fact directory
  file:
    path: "{{ facts__dir|d('/etc/ansible/facts.d') }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: ['nginx', 'nginx-facts']

- name: Insert custom fact file
  copy:
    src: files/nginx.facts.py
    dest: "{{ facts__dir|d('/etc/ansible/facts.d') }}/nginx.fact"
    mode: 0755
  tags: ['nginx', 'nginx-facts']
