---

- name: Add nginx repository GPG key to apt keyring
  apt_key:
    id: '{{ item.id }}'
    keyserver: '{{ item.keyserver }}'
    state: "{{ item.state|d('present') }}"
  with_items: '{{ nginx__provider_gpg_keys[ansible_distribution] }}'
  register: _nginx__apt_key
  ignore_errors: '{{ httpproxy is defined }}'
  tags: ['nginx', 'nginx-install']

- name: Add repository APT key using http proxy
  command: apt-key adv --keyserver-options "http-proxy={{ httpproxy }}" --keyserver '{{ item.keyserver }}' --recv-keys '{{ item.id }}'
  with_items: '{{ nginx__provider_gpg_keys[ansible_distribution] }}'
  when: _nginx__apt_key is failed and httpproxy is defined
  tags: ['nginx', 'nginx-install']

- name: Add nginx repository for Debian
  apt_repository:
    repo: '{{ item }}'
    filename: nginx
  with_items: '{{ nginx__provider_repositories[ansible_distribution] }}'
  tags: ['nginx', 'nginx-install']
