---
# tasks file for nginx

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Importing initialization tasks
  import_tasks: init.yml
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['nginx', 'nginx-install']

- name: Importing configuration tasks
  import_tasks: configure.yml
  tags: ['nginx', 'nginx-configure']

- name: Importing service tasks
  import_tasks: service.yml
  tags: ['nginx', 'nginx-service']

- name: Optionally importing monitoring tasks
  include_tasks: 'monitoring/{{ monitoring_backend }}.yml'
  with_items: '{{ [nginx__monitoring]|flatten|unique|list }}'
  when: nginx__monitoring is defined
  loop_control:
    loop_var: monitoring_backend
  tags: ['nginx', 'nginx-monitoring']

- name: Optionally import facts tasks
  include_tasks: facts.yml
  when: nginx__facts|bool
  tags: ['nginx', 'nginx-facts']
